// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAgentsByUser = `-- name: CountAgentsByUser :one
SELECT COUNT(*) FROM agents WHERE user_id = ?
`

func (q *Queries) CountAgentsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, user_id, name, description, system_prompt, model_provider, model_name, config_yaml, max_turns, timeout_seconds)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, team_id, name, description, system_prompt, model_provider, model_name, config_yaml, max_turns, timeout_seconds, enabled, created_at, updated_at
`

type CreateAgentParams struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	SystemPrompt   string         `json:"system_prompt"`
	ModelProvider  string         `json:"model_provider"`
	ModelName      string         `json:"model_name"`
	ConfigYaml     string         `json:"config_yaml"`
	MaxTurns       int64          `json:"max_turns"`
	TimeoutSeconds int64          `json:"timeout_seconds"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ModelProvider,
		arg.ModelName,
		arg.ConfigYaml,
		arg.MaxTurns,
		arg.TimeoutSeconds,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ModelProvider,
		&i.ModelName,
		&i.ConfigYaml,
		&i.MaxTurns,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, user_id, team_id, name, description, system_prompt, model_provider, model_name, config_yaml, max_turns, timeout_seconds, enabled, created_at, updated_at FROM agents WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ModelProvider,
		&i.ModelName,
		&i.ConfigYaml,
		&i.MaxTurns,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsByUser = `-- name: ListAgentsByUser :many
SELECT id, user_id, team_id, name, description, system_prompt, model_provider, model_name, config_yaml, max_turns, timeout_seconds, enabled, created_at, updated_at FROM agents WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAgentsByUser(ctx context.Context, userID string) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.ModelProvider,
			&i.ModelName,
			&i.ConfigYaml,
			&i.MaxTurns,
			&i.TimeoutSeconds,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :exec
UPDATE agents
SET name = ?, description = ?, system_prompt = ?, model_provider = ?, model_name = ?,
    config_yaml = ?, max_turns = ?, timeout_seconds = ?, enabled = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateAgentParams struct {
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	SystemPrompt   string         `json:"system_prompt"`
	ModelProvider  string         `json:"model_provider"`
	ModelName      string         `json:"model_name"`
	ConfigYaml     string         `json:"config_yaml"`
	MaxTurns       int64          `json:"max_turns"`
	TimeoutSeconds int64          `json:"timeout_seconds"`
	Enabled        bool           `json:"enabled"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) error {
	_, err := q.db.ExecContext(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ModelProvider,
		arg.ModelName,
		arg.ConfigYaml,
		arg.MaxTurns,
		arg.TimeoutSeconds,
		arg.Enabled,
		arg.ID,
	)
	return err
}
