// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
	"time"
)

const clearDefaultAPIKey = `-- name: ClearDefaultAPIKey :exec
UPDATE api_keys SET is_default = false WHERE user_id = ? AND provider = ?
`

type ClearDefaultAPIKeyParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) ClearDefaultAPIKey(ctx context.Context, arg ClearDefaultAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, clearDefaultAPIKey, arg.UserID, arg.Provider)
	return err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, user_id, provider, label, key_enc, key_hint, is_default, base_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, provider, label, key_enc, key_hint, is_default, base_url, created_at
`

type CreateAPIKeyParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Provider  string `json:"provider"`
	Label     string `json:"label"`
	KeyEnc    []byte `json:"key_enc"`
	KeyHint   string `json:"key_hint"`
	IsDefault bool   `json:"is_default"`
	BaseUrl   string `json:"base_url"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Label,
		arg.KeyEnc,
		arg.KeyHint,
		arg.IsDefault,
		arg.BaseUrl,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Label,
		&i.KeyEnc,
		&i.KeyHint,
		&i.IsDefault,
		&i.BaseUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = ? AND user_id = ?
`

type DeleteAPIKeyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, arg.ID, arg.UserID)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, user_id, provider, label, key_enc, key_hint, is_default, base_url, created_at FROM api_keys WHERE id = ? AND user_id = ?
`

type GetAPIKeyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, arg.ID, arg.UserID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Label,
		&i.KeyEnc,
		&i.KeyHint,
		&i.IsDefault,
		&i.BaseUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultAPIKey = `-- name: GetDefaultAPIKey :one
SELECT id, user_id, provider, label, key_enc, key_hint, is_default, base_url, created_at FROM api_keys WHERE user_id = ? AND provider = ? AND is_default = true
`

type GetDefaultAPIKeyParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetDefaultAPIKey(ctx context.Context, arg GetDefaultAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getDefaultAPIKey, arg.UserID, arg.Provider)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Label,
		&i.KeyEnc,
		&i.KeyHint,
		&i.IsDefault,
		&i.BaseUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, provider, label, key_hint, is_default, base_url, created_at
FROM api_keys WHERE user_id = ? ORDER BY created_at DESC
`

type ListAPIKeysByUserRow struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Provider  string    `json:"provider"`
	Label     string    `json:"label"`
	KeyHint   string    `json:"key_hint"`
	IsDefault bool      `json:"is_default"`
	BaseUrl   string    `json:"base_url"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID string) ([]ListAPIKeysByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByUserRow{}
	for rows.Next() {
		var i ListAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Label,
			&i.KeyHint,
			&i.IsDefault,
			&i.BaseUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
