// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT COUNT(*) FROM audit_log WHERE user_id = ?
`

func (q *Queries) CountAuditLog(ctx context.Context, userID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLog, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (user_id, action, resource_id, metadata, ip_address)
VALUES (?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	UserID     sql.NullString `json:"user_id"`
	Action     string         `json:"action"`
	ResourceID sql.NullString `json:"resource_id"`
	Metadata   sql.NullString `json:"metadata"`
	IpAddress  sql.NullString `json:"ip_address"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceID,
		arg.Metadata,
		arg.IpAddress,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, user_id, "action", resource_id, metadata, ip_address, created_at FROM audit_log
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAuditLogParams struct {
	UserID sql.NullString `json:"user_id"`
	Limit  int64          `json:"limit"`
	Offset int64          `json:"offset"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceID,
			&i.Metadata,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
