// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package sqlc

import (
	"context"
	"time"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO user_credentials (id, user_id, name, value_enc, value_hint, skill_name, description)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, value_enc, value_hint, skill_name, description, created_at, updated_at
`

type CreateCredentialParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	Name        string `json:"name"`
	ValueEnc    []byte `json:"value_enc"`
	ValueHint   string `json:"value_hint"`
	SkillName   string `json:"skill_name"`
	Description string `json:"description"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ValueEnc,
		arg.ValueHint,
		arg.SkillName,
		arg.Description,
	)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ValueEnc,
		&i.ValueHint,
		&i.SkillName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM user_credentials WHERE id = ? AND user_id = ?
`

type DeleteCredentialParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, arg.ID, arg.UserID)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, user_id, name, value_enc, value_hint, skill_name, description, created_at, updated_at FROM user_credentials WHERE id = ? AND user_id = ?
`

type GetCredentialParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, getCredential, arg.ID, arg.UserID)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ValueEnc,
		&i.ValueHint,
		&i.SkillName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByName = `-- name: GetCredentialByName :one
SELECT id, user_id, name, value_enc, value_hint, skill_name, description, created_at, updated_at FROM user_credentials WHERE user_id = ? AND name = ? AND skill_name = ?
`

type GetCredentialByNameParams struct {
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	SkillName string `json:"skill_name"`
}

func (q *Queries) GetCredentialByName(ctx context.Context, arg GetCredentialByNameParams) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByName, arg.UserID, arg.Name, arg.SkillName)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ValueEnc,
		&i.ValueHint,
		&i.SkillName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCredentialValues = `-- name: ListAllCredentialValues :many
SELECT name, value_enc, skill_name FROM user_credentials
WHERE user_id = ?
ORDER BY skill_name DESC, name
`

type ListAllCredentialValuesRow struct {
	Name      string `json:"name"`
	ValueEnc  []byte `json:"value_enc"`
	SkillName string `json:"skill_name"`
}

func (q *Queries) ListAllCredentialValues(ctx context.Context, userID string) ([]ListAllCredentialValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllCredentialValues, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCredentialValuesRow{}
	for rows.Next() {
		var i ListAllCredentialValuesRow
		if err := rows.Scan(&i.Name, &i.ValueEnc, &i.SkillName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByUser = `-- name: ListCredentialsByUser :many
SELECT id, user_id, name, value_hint, skill_name, description, created_at, updated_at
FROM user_credentials WHERE user_id = ? ORDER BY name, skill_name
`

type ListCredentialsByUserRow struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Name        string    `json:"name"`
	ValueHint   string    `json:"value_hint"`
	SkillName   string    `json:"skill_name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListCredentialsByUser(ctx context.Context, userID string) ([]ListCredentialsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsByUserRow{}
	for rows.Next() {
		var i ListCredentialsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ValueHint,
			&i.SkillName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsForSkill = `-- name: ListCredentialsForSkill :many
SELECT id, user_id, name, value_enc, value_hint, skill_name, description, created_at, updated_at FROM user_credentials
WHERE user_id = ? AND (skill_name = ? OR skill_name = '')
ORDER BY skill_name DESC
`

type ListCredentialsForSkillParams struct {
	UserID    string `json:"user_id"`
	SkillName string `json:"skill_name"`
}

func (q *Queries) ListCredentialsForSkill(ctx context.Context, arg ListCredentialsForSkillParams) ([]UserCredential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialsForSkill, arg.UserID, arg.SkillName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserCredential{}
	for rows.Next() {
		var i UserCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ValueEnc,
			&i.ValueHint,
			&i.SkillName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE user_credentials
SET value_enc = ?, value_hint = ?, description = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateCredentialParams struct {
	ValueEnc    []byte `json:"value_enc"`
	ValueHint   string `json:"value_hint"`
	Description string `json:"description"`
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateCredential,
		arg.ValueEnc,
		arg.ValueHint,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	return err
}
