// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Agent struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	TeamID         sql.NullString `json:"team_id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	SystemPrompt   string         `json:"system_prompt"`
	ModelProvider  string         `json:"model_provider"`
	ModelName      string         `json:"model_name"`
	ConfigYaml     string         `json:"config_yaml"`
	MaxTurns       int64          `json:"max_turns"`
	TimeoutSeconds int64          `json:"timeout_seconds"`
	Enabled        bool           `json:"enabled"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type AgentSkill struct {
	AgentID    string         `json:"agent_id"`
	SkillID    string         `json:"skill_id"`
	Position   int64          `json:"position"`
	ConfigJson sql.NullString `json:"config_json"`
}

type ApiKey struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Provider  string    `json:"provider"`
	Label     string    `json:"label"`
	KeyEnc    []byte    `json:"key_enc"`
	KeyHint   string    `json:"key_hint"`
	IsDefault bool      `json:"is_default"`
	BaseUrl   string    `json:"base_url"`
	CreatedAt time.Time `json:"created_at"`
}

type AuditLog struct {
	ID         int64          `json:"id"`
	UserID     sql.NullString `json:"user_id"`
	Action     string         `json:"action"`
	ResourceID sql.NullString `json:"resource_id"`
	Metadata   sql.NullString `json:"metadata"`
	IpAddress  sql.NullString `json:"ip_address"`
	CreatedAt  time.Time      `json:"created_at"`
}

type Run struct {
	ID            string          `json:"id"`
	AgentID       string          `json:"agent_id"`
	TeamID        sql.NullString  `json:"team_id"`
	ParentRunID   sql.NullString  `json:"parent_run_id"`
	Depth         int64           `json:"depth"`
	Mission       string          `json:"mission"`
	ModelProvider string          `json:"model_provider"`
	ModelName     string          `json:"model_name"`
	Status        string          `json:"status"`
	OutputText    sql.NullString  `json:"output_text"`
	ErrorMessage  sql.NullString  `json:"error_message"`
	TotalTurns    sql.NullInt64   `json:"total_turns"`
	InputTokens   sql.NullInt64   `json:"input_tokens"`
	OutputTokens  sql.NullInt64   `json:"output_tokens"`
	CostUsd       sql.NullFloat64 `json:"cost_usd"`
	DurationMs    sql.NullInt64   `json:"duration_ms"`
	CreatedAt     time.Time       `json:"created_at"`
	StartedAt     sql.NullTime    `json:"started_at"`
	CompletedAt   sql.NullTime    `json:"completed_at"`
}

type RunEvent struct {
	ID         int64          `json:"id"`
	RunID      string         `json:"run_id"`
	Seq        int64          `json:"seq"`
	EventType  string         `json:"event_type"`
	DataJson   sql.NullString `json:"data_json"`
	OccurredAt time.Time      `json:"occurred_at"`
}

type Schedule struct {
	ID                string         `json:"id"`
	UserID            string         `json:"user_id"`
	AgentID           string         `json:"agent_id"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	ScheduleType      string         `json:"schedule_type"`
	CronExpr          string         `json:"cron_expr"`
	IntervalSeconds   int64          `json:"interval_seconds"`
	Timezone          string         `json:"timezone"`
	Mission           string         `json:"mission"`
	Enabled           bool           `json:"enabled"`
	OverlapPolicy     string         `json:"overlap_policy"`
	MaxRetries        int64          `json:"max_retries"`
	NextRunAt         sql.NullTime   `json:"next_run_at"`
	LastRunAt         sql.NullTime   `json:"last_run_at"`
	LastRunStatus     sql.NullString `json:"last_run_status"`
	LastRunID         sql.NullString `json:"last_run_id"`
	LastError         sql.NullString `json:"last_error"`
	ConsecutiveErrors int64          `json:"consecutive_errors"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type Skill struct {
	ID          string         `json:"id"`
	UserID      sql.NullString `json:"user_id"`
	SourceID    sql.NullString `json:"source_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Tier        string         `json:"tier"`
	Version     string         `json:"version"`
	SkillMd     string         `json:"skill_md"`
	Tags        string         `json:"tags"`
	SourceUrl   sql.NullString `json:"source_url"`
	Enabled     bool           `json:"enabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type SkillSource struct {
	ID         string         `json:"id"`
	UserID     sql.NullString `json:"user_id"`
	Url        string         `json:"url"`
	Label      string         `json:"label"`
	IsDefault  bool           `json:"is_default"`
	LastSynced sql.NullTime   `json:"last_synced"`
	SkillCount int64          `json:"skill_count"`
	Status     string         `json:"status"`
	ErrorMsg   sql.NullString `json:"error_msg"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Team struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	OwnerID   string    `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TeamInvitation struct {
	ID        string    `json:"id"`
	TeamID    string    `json:"team_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	InvitedBy string    `json:"invited_by"`
	Status    string    `json:"status"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type TeamMember struct {
	TeamID   string    `json:"team_id"`
	UserID   string    `json:"user_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

type User struct {
	ID            string         `json:"id"`
	Email         string         `json:"email"`
	Name          string         `json:"name"`
	PasswordHash  sql.NullString `json:"password_hash"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	OauthProvider sql.NullString `json:"oauth_provider"`
	OauthID       sql.NullString `json:"oauth_id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type UserCredential struct {
	ID          string    `json:"id"`
	UserID      string    `json:"user_id"`
	Name        string    `json:"name"`
	ValueEnc    []byte    `json:"value_enc"`
	ValueHint   string    `json:"value_hint"`
	SkillName   string    `json:"skill_name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
