// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Agent struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	SystemPrompt   string         `json:"system_prompt"`
	ModelProvider  string         `json:"model_provider"`
	ModelName      string         `json:"model_name"`
	ConfigYaml     string         `json:"config_yaml"`
	MaxTurns       int64          `json:"max_turns"`
	TimeoutSeconds int64          `json:"timeout_seconds"`
	Enabled        bool           `json:"enabled"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type AgentSkill struct {
	AgentID    string         `json:"agent_id"`
	SkillID    string         `json:"skill_id"`
	Position   int64          `json:"position"`
	ConfigJson sql.NullString `json:"config_json"`
}

type ApiKey struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Provider  string    `json:"provider"`
	Label     string    `json:"label"`
	KeyEnc    []byte    `json:"key_enc"`
	KeyHint   string    `json:"key_hint"`
	IsDefault bool      `json:"is_default"`
	BaseUrl   string    `json:"base_url"`
	CreatedAt time.Time `json:"created_at"`
}

type Run struct {
	ID            string          `json:"id"`
	AgentID       string          `json:"agent_id"`
	Mission       string          `json:"mission"`
	ModelProvider string          `json:"model_provider"`
	ModelName     string          `json:"model_name"`
	Status        string          `json:"status"`
	OutputText    sql.NullString  `json:"output_text"`
	ErrorMessage  sql.NullString  `json:"error_message"`
	TotalTurns    sql.NullInt64   `json:"total_turns"`
	InputTokens   sql.NullInt64   `json:"input_tokens"`
	OutputTokens  sql.NullInt64   `json:"output_tokens"`
	CostUsd       sql.NullFloat64 `json:"cost_usd"`
	DurationMs    sql.NullInt64   `json:"duration_ms"`
	CreatedAt     time.Time       `json:"created_at"`
	StartedAt     sql.NullTime    `json:"started_at"`
	CompletedAt   sql.NullTime    `json:"completed_at"`
}

type RunEvent struct {
	ID         int64          `json:"id"`
	RunID      string         `json:"run_id"`
	Seq        int64          `json:"seq"`
	EventType  string         `json:"event_type"`
	DataJson   sql.NullString `json:"data_json"`
	OccurredAt time.Time      `json:"occurred_at"`
}

type Skill struct {
	ID          string         `json:"id"`
	UserID      sql.NullString `json:"user_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Tier        string         `json:"tier"`
	Version     string         `json:"version"`
	SkillMd     string         `json:"skill_md"`
	Tags        string         `json:"tags"`
	SourceUrl   sql.NullString `json:"source_url"`
	Enabled     bool           `json:"enabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	Name         string         `json:"name"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
