// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countRunsByAgent = `-- name: CountRunsByAgent :one
SELECT COUNT(*) FROM runs WHERE agent_id = ?
`

func (q *Queries) CountRunsByAgent(ctx context.Context, agentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunsByAgent, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunsByUser = `-- name: CountRunsByUser :one
SELECT COUNT(*) FROM runs r
JOIN agents a ON r.agent_id = a.id
WHERE a.user_id = ?
`

func (q *Queries) CountRunsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, agent_id, mission, model_provider, model_name, status)
VALUES (?, ?, ?, ?, ?, 'queued')
RETURNING id, agent_id, team_id, parent_run_id, depth, mission, model_provider, model_name, status, output_text, error_message, total_turns, input_tokens, output_tokens, cost_usd, duration_ms, created_at, started_at, completed_at
`

type CreateRunParams struct {
	ID            string `json:"id"`
	AgentID       string `json:"agent_id"`
	Mission       string `json:"mission"`
	ModelProvider string `json:"model_provider"`
	ModelName     string `json:"model_name"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.ID,
		arg.AgentID,
		arg.Mission,
		arg.ModelProvider,
		arg.ModelName,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TeamID,
		&i.ParentRunID,
		&i.Depth,
		&i.Mission,
		&i.ModelProvider,
		&i.ModelName,
		&i.Status,
		&i.OutputText,
		&i.ErrorMessage,
		&i.TotalTurns,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.DurationMs,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, agent_id, team_id, parent_run_id, depth, mission, model_provider, model_name, status, output_text, error_message, total_turns, input_tokens, output_tokens, cost_usd, duration_ms, created_at, started_at, completed_at FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TeamID,
		&i.ParentRunID,
		&i.Depth,
		&i.Mission,
		&i.ModelProvider,
		&i.ModelName,
		&i.Status,
		&i.OutputText,
		&i.ErrorMessage,
		&i.TotalTurns,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CostUsd,
		&i.DurationMs,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertRunEvent = `-- name: InsertRunEvent :exec
INSERT INTO run_events (run_id, seq, event_type, data_json)
VALUES (?, ?, ?, ?)
`

type InsertRunEventParams struct {
	RunID     string         `json:"run_id"`
	Seq       int64          `json:"seq"`
	EventType string         `json:"event_type"`
	DataJson  sql.NullString `json:"data_json"`
}

func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) error {
	_, err := q.db.ExecContext(ctx, insertRunEvent,
		arg.RunID,
		arg.Seq,
		arg.EventType,
		arg.DataJson,
	)
	return err
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT id, run_id, seq, event_type, data_json, occurred_at FROM run_events WHERE run_id = ? ORDER BY seq
`

func (q *Queries) ListRunEvents(ctx context.Context, runID string) ([]RunEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRunEvents, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunEvent{}
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.EventType,
			&i.DataJson,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByAgent = `-- name: ListRunsByAgent :many
SELECT id, agent_id, team_id, parent_run_id, depth, mission, model_provider, model_name, status, output_text, error_message, total_turns, input_tokens, output_tokens, cost_usd, duration_ms, created_at, started_at, completed_at FROM runs WHERE agent_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListRunsByAgentParams struct {
	AgentID string `json:"agent_id"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListRunsByAgent(ctx context.Context, arg ListRunsByAgentParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByAgent, arg.AgentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TeamID,
			&i.ParentRunID,
			&i.Depth,
			&i.Mission,
			&i.ModelProvider,
			&i.ModelName,
			&i.Status,
			&i.OutputText,
			&i.ErrorMessage,
			&i.TotalTurns,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.DurationMs,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByUser = `-- name: ListRunsByUser :many
SELECT r.id, r.agent_id, r.team_id, r.parent_run_id, r.depth, r.mission, r.model_provider, r.model_name, r.status, r.output_text, r.error_message, r.total_turns, r.input_tokens, r.output_tokens, r.cost_usd, r.duration_ms, r.created_at, r.started_at, r.completed_at FROM runs r
JOIN agents a ON r.agent_id = a.id
WHERE a.user_id = ?
ORDER BY r.created_at DESC LIMIT ? OFFSET ?
`

type ListRunsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListRunsByUser(ctx context.Context, arg ListRunsByUserParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TeamID,
			&i.ParentRunID,
			&i.Depth,
			&i.Mission,
			&i.ModelProvider,
			&i.ModelName,
			&i.Status,
			&i.OutputText,
			&i.ErrorMessage,
			&i.TotalTurns,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.DurationMs,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByUserFiltered = `-- name: ListRunsByUserFiltered :many
SELECT r.id, r.agent_id, r.team_id, r.parent_run_id, r.depth, r.mission, r.model_provider, r.model_name, r.status, r.output_text, r.error_message, r.total_turns, r.input_tokens, r.output_tokens, r.cost_usd, r.duration_ms, r.created_at, r.started_at, r.completed_at FROM runs r
JOIN agents a ON r.agent_id = a.id
WHERE a.user_id = ?
  AND (CAST(? AS TEXT) = '' OR r.status = CAST(? AS TEXT))
  AND (CAST(? AS TEXT) = '' OR r.agent_id = CAST(? AS TEXT))
ORDER BY r.created_at DESC LIMIT ? OFFSET ?
`

type ListRunsByUserFilteredParams struct {
	UserID  string `json:"user_id"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 string `json:"column_5"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListRunsByUserFiltered(ctx context.Context, arg ListRunsByUserFilteredParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByUserFiltered,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TeamID,
			&i.ParentRunID,
			&i.Depth,
			&i.Mission,
			&i.ModelProvider,
			&i.ModelName,
			&i.Status,
			&i.OutputText,
			&i.ErrorMessage,
			&i.TotalTurns,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.DurationMs,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunResult = `-- name: UpdateRunResult :exec
UPDATE runs
SET status = ?, output_text = ?, error_message = ?,
    total_turns = ?, input_tokens = ?, output_tokens = ?,
    cost_usd = ?, duration_ms = ?, completed_at = ?
WHERE id = ?
`

type UpdateRunResultParams struct {
	Status       string          `json:"status"`
	OutputText   sql.NullString  `json:"output_text"`
	ErrorMessage sql.NullString  `json:"error_message"`
	TotalTurns   sql.NullInt64   `json:"total_turns"`
	InputTokens  sql.NullInt64   `json:"input_tokens"`
	OutputTokens sql.NullInt64   `json:"output_tokens"`
	CostUsd      sql.NullFloat64 `json:"cost_usd"`
	DurationMs   sql.NullInt64   `json:"duration_ms"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	ID           string          `json:"id"`
}

func (q *Queries) UpdateRunResult(ctx context.Context, arg UpdateRunResultParams) error {
	_, err := q.db.ExecContext(ctx, updateRunResult,
		arg.Status,
		arg.OutputText,
		arg.ErrorMessage,
		arg.TotalTurns,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.DurationMs,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE runs SET status = ?, started_at = ?, completed_at = ? WHERE id = ?
`

type UpdateRunStatusParams struct {
	Status      string       `json:"status"`
	StartedAt   sql.NullTime `json:"started_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	ID          string       `json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStatus,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}
