// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (id, user_id, agent_id, name, description, schedule_type, cron_expr, interval_seconds, timezone, mission, enabled, overlap_policy, max_retries, next_run_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, agent_id, name, description, schedule_type, cron_expr, interval_seconds, timezone, mission, enabled, overlap_policy, max_retries, next_run_at, last_run_at, last_run_status, last_run_id, last_error, consecutive_errors, created_at, updated_at
`

type CreateScheduleParams struct {
	ID              string       `json:"id"`
	UserID          string       `json:"user_id"`
	AgentID         string       `json:"agent_id"`
	Name            string       `json:"name"`
	Description     string       `json:"description"`
	ScheduleType    string       `json:"schedule_type"`
	CronExpr        string       `json:"cron_expr"`
	IntervalSeconds int64        `json:"interval_seconds"`
	Timezone        string       `json:"timezone"`
	Mission         string       `json:"mission"`
	Enabled         bool         `json:"enabled"`
	OverlapPolicy   string       `json:"overlap_policy"`
	MaxRetries      int64        `json:"max_retries"`
	NextRunAt       sql.NullTime `json:"next_run_at"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.ID,
		arg.UserID,
		arg.AgentID,
		arg.Name,
		arg.Description,
		arg.ScheduleType,
		arg.CronExpr,
		arg.IntervalSeconds,
		arg.Timezone,
		arg.Mission,
		arg.Enabled,
		arg.OverlapPolicy,
		arg.MaxRetries,
		arg.NextRunAt,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.ScheduleType,
		&i.CronExpr,
		&i.IntervalSeconds,
		&i.Timezone,
		&i.Mission,
		&i.Enabled,
		&i.OverlapPolicy,
		&i.MaxRetries,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.LastRunID,
		&i.LastError,
		&i.ConsecutiveErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = ? AND user_id = ?
`

type DeleteScheduleParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, arg.ID, arg.UserID)
	return err
}

const disableSchedule = `-- name: DisableSchedule :exec
UPDATE schedules SET enabled = false, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND user_id = ?
`

type DisableScheduleParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DisableSchedule(ctx context.Context, arg DisableScheduleParams) error {
	_, err := q.db.ExecContext(ctx, disableSchedule, arg.ID, arg.UserID)
	return err
}

const enableSchedule = `-- name: EnableSchedule :exec
UPDATE schedules SET enabled = true, consecutive_errors = 0, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND user_id = ?
`

type EnableScheduleParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) EnableSchedule(ctx context.Context, arg EnableScheduleParams) error {
	_, err := q.db.ExecContext(ctx, enableSchedule, arg.ID, arg.UserID)
	return err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, user_id, agent_id, name, description, schedule_type, cron_expr, interval_seconds, timezone, mission, enabled, overlap_policy, max_retries, next_run_at, last_run_at, last_run_status, last_run_id, last_error, consecutive_errors, created_at, updated_at FROM schedules WHERE id = ? AND user_id = ?
`

type GetScheduleParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSchedule(ctx context.Context, arg GetScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, arg.ID, arg.UserID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.ScheduleType,
		&i.CronExpr,
		&i.IntervalSeconds,
		&i.Timezone,
		&i.Mission,
		&i.Enabled,
		&i.OverlapPolicy,
		&i.MaxRetries,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.LastRunID,
		&i.LastError,
		&i.ConsecutiveErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueSchedules = `-- name: ListDueSchedules :many
SELECT s.id, s.user_id, s.agent_id, s.name, s.description, s.schedule_type, s.cron_expr, s.interval_seconds, s.timezone, s.mission, s.enabled, s.overlap_policy, s.max_retries, s.next_run_at, s.last_run_at, s.last_run_status, s.last_run_id, s.last_error, s.consecutive_errors, s.created_at, s.updated_at, a.model_provider, a.model_name, a.system_prompt, a.max_turns, a.timeout_seconds
FROM schedules s
JOIN agents a ON s.agent_id = a.id
WHERE s.enabled = true AND s.next_run_at <= ?
ORDER BY s.next_run_at ASC
`

type ListDueSchedulesRow struct {
	ID                string         `json:"id"`
	UserID            string         `json:"user_id"`
	AgentID           string         `json:"agent_id"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	ScheduleType      string         `json:"schedule_type"`
	CronExpr          string         `json:"cron_expr"`
	IntervalSeconds   int64          `json:"interval_seconds"`
	Timezone          string         `json:"timezone"`
	Mission           string         `json:"mission"`
	Enabled           bool           `json:"enabled"`
	OverlapPolicy     string         `json:"overlap_policy"`
	MaxRetries        int64          `json:"max_retries"`
	NextRunAt         sql.NullTime   `json:"next_run_at"`
	LastRunAt         sql.NullTime   `json:"last_run_at"`
	LastRunStatus     sql.NullString `json:"last_run_status"`
	LastRunID         sql.NullString `json:"last_run_id"`
	LastError         sql.NullString `json:"last_error"`
	ConsecutiveErrors int64          `json:"consecutive_errors"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	ModelProvider     string         `json:"model_provider"`
	ModelName         string         `json:"model_name"`
	SystemPrompt      string         `json:"system_prompt"`
	MaxTurns          int64          `json:"max_turns"`
	TimeoutSeconds    int64          `json:"timeout_seconds"`
}

func (q *Queries) ListDueSchedules(ctx context.Context, nextRunAt sql.NullTime) ([]ListDueSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueSchedules, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueSchedulesRow{}
	for rows.Next() {
		var i ListDueSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.ScheduleType,
			&i.CronExpr,
			&i.IntervalSeconds,
			&i.Timezone,
			&i.Mission,
			&i.Enabled,
			&i.OverlapPolicy,
			&i.MaxRetries,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.LastRunID,
			&i.LastError,
			&i.ConsecutiveErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelProvider,
			&i.ModelName,
			&i.SystemPrompt,
			&i.MaxTurns,
			&i.TimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, user_id, agent_id, name, description, schedule_type, cron_expr, interval_seconds, timezone, mission, enabled, overlap_policy, max_retries, next_run_at, last_run_at, last_run_status, last_run_id, last_error, consecutive_errors, created_at, updated_at FROM schedules WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListSchedules(ctx context.Context, userID string) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.ScheduleType,
			&i.CronExpr,
			&i.IntervalSeconds,
			&i.Timezone,
			&i.Mission,
			&i.Enabled,
			&i.OverlapPolicy,
			&i.MaxRetries,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.LastRunID,
			&i.LastError,
			&i.ConsecutiveErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByAgent = `-- name: ListSchedulesByAgent :many
SELECT id, user_id, agent_id, name, description, schedule_type, cron_expr, interval_seconds, timezone, mission, enabled, overlap_policy, max_retries, next_run_at, last_run_at, last_run_status, last_run_id, last_error, consecutive_errors, created_at, updated_at FROM schedules WHERE agent_id = ? AND user_id = ? ORDER BY created_at DESC
`

type ListSchedulesByAgentParams struct {
	AgentID string `json:"agent_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) ListSchedulesByAgent(ctx context.Context, arg ListSchedulesByAgentParams) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesByAgent, arg.AgentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.ScheduleType,
			&i.CronExpr,
			&i.IntervalSeconds,
			&i.Timezone,
			&i.Mission,
			&i.Enabled,
			&i.OverlapPolicy,
			&i.MaxRetries,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.LastRunID,
			&i.LastError,
			&i.ConsecutiveErrors,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules SET
    name = ?,
    description = ?,
    schedule_type = ?,
    cron_expr = ?,
    interval_seconds = ?,
    timezone = ?,
    mission = ?,
    enabled = ?,
    overlap_policy = ?,
    max_retries = ?,
    next_run_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, agent_id, name, description, schedule_type, cron_expr, interval_seconds, timezone, mission, enabled, overlap_policy, max_retries, next_run_at, last_run_at, last_run_status, last_run_id, last_error, consecutive_errors, created_at, updated_at
`

type UpdateScheduleParams struct {
	Name            string       `json:"name"`
	Description     string       `json:"description"`
	ScheduleType    string       `json:"schedule_type"`
	CronExpr        string       `json:"cron_expr"`
	IntervalSeconds int64        `json:"interval_seconds"`
	Timezone        string       `json:"timezone"`
	Mission         string       `json:"mission"`
	Enabled         bool         `json:"enabled"`
	OverlapPolicy   string       `json:"overlap_policy"`
	MaxRetries      int64        `json:"max_retries"`
	NextRunAt       sql.NullTime `json:"next_run_at"`
	ID              string       `json:"id"`
	UserID          string       `json:"user_id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, updateSchedule,
		arg.Name,
		arg.Description,
		arg.ScheduleType,
		arg.CronExpr,
		arg.IntervalSeconds,
		arg.Timezone,
		arg.Mission,
		arg.Enabled,
		arg.OverlapPolicy,
		arg.MaxRetries,
		arg.NextRunAt,
		arg.ID,
		arg.UserID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.ScheduleType,
		&i.CronExpr,
		&i.IntervalSeconds,
		&i.Timezone,
		&i.Mission,
		&i.Enabled,
		&i.OverlapPolicy,
		&i.MaxRetries,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.LastRunID,
		&i.LastError,
		&i.ConsecutiveErrors,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScheduleAfterRun = `-- name: UpdateScheduleAfterRun :exec
UPDATE schedules SET
    last_run_at = ?,
    last_run_status = ?,
    last_run_id = ?,
    last_error = ?,
    consecutive_errors = ?,
    next_run_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateScheduleAfterRunParams struct {
	LastRunAt         sql.NullTime   `json:"last_run_at"`
	LastRunStatus     sql.NullString `json:"last_run_status"`
	LastRunID         sql.NullString `json:"last_run_id"`
	LastError         sql.NullString `json:"last_error"`
	ConsecutiveErrors int64          `json:"consecutive_errors"`
	NextRunAt         sql.NullTime   `json:"next_run_at"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateScheduleAfterRun(ctx context.Context, arg UpdateScheduleAfterRunParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduleAfterRun,
		arg.LastRunAt,
		arg.LastRunStatus,
		arg.LastRunID,
		arg.LastError,
		arg.ConsecutiveErrors,
		arg.NextRunAt,
		arg.ID,
	)
	return err
}
