// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skill_sources.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSkillSource = `-- name: CreateSkillSource :one
INSERT INTO skill_sources (id, user_id, url, label, is_default)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, url, label, is_default, last_synced, skill_count, status, error_msg, created_at, updated_at
`

type CreateSkillSourceParams struct {
	ID        string         `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	Url       string         `json:"url"`
	Label     string         `json:"label"`
	IsDefault bool           `json:"is_default"`
}

func (q *Queries) CreateSkillSource(ctx context.Context, arg CreateSkillSourceParams) (SkillSource, error) {
	row := q.db.QueryRowContext(ctx, createSkillSource,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.Label,
		arg.IsDefault,
	)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Label,
		&i.IsDefault,
		&i.LastSynced,
		&i.SkillCount,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkillSource = `-- name: DeleteSkillSource :exec
DELETE FROM skill_sources WHERE id = ? AND is_default = false
`

func (q *Queries) DeleteSkillSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSkillSource, id)
	return err
}

const getDefaultSkillSource = `-- name: GetDefaultSkillSource :one
SELECT id, user_id, url, label, is_default, last_synced, skill_count, status, error_msg, created_at, updated_at FROM skill_sources WHERE is_default = true LIMIT 1
`

func (q *Queries) GetDefaultSkillSource(ctx context.Context) (SkillSource, error) {
	row := q.db.QueryRowContext(ctx, getDefaultSkillSource)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Label,
		&i.IsDefault,
		&i.LastSynced,
		&i.SkillCount,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillSource = `-- name: GetSkillSource :one
SELECT id, user_id, url, label, is_default, last_synced, skill_count, status, error_msg, created_at, updated_at FROM skill_sources WHERE id = ?
`

func (q *Queries) GetSkillSource(ctx context.Context, id string) (SkillSource, error) {
	row := q.db.QueryRowContext(ctx, getSkillSource, id)
	var i SkillSource
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Label,
		&i.IsDefault,
		&i.LastSynced,
		&i.SkillCount,
		&i.Status,
		&i.ErrorMsg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkillSources = `-- name: ListSkillSources :many
SELECT id, user_id, url, label, is_default, last_synced, skill_count, status, error_msg, created_at, updated_at FROM skill_sources ORDER BY is_default DESC, label
`

func (q *Queries) ListSkillSources(ctx context.Context) ([]SkillSource, error) {
	rows, err := q.db.QueryContext(ctx, listSkillSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillSource{}
	for rows.Next() {
		var i SkillSource
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Label,
			&i.IsDefault,
			&i.LastSynced,
			&i.SkillCount,
			&i.Status,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillSourcesByUser = `-- name: ListSkillSourcesByUser :many
SELECT id, user_id, url, label, is_default, last_synced, skill_count, status, error_msg, created_at, updated_at FROM skill_sources
WHERE user_id = ? OR user_id IS NULL
ORDER BY is_default DESC, label
`

func (q *Queries) ListSkillSourcesByUser(ctx context.Context, userID sql.NullString) ([]SkillSource, error) {
	rows, err := q.db.QueryContext(ctx, listSkillSourcesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillSource{}
	for rows.Next() {
		var i SkillSource
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Label,
			&i.IsDefault,
			&i.LastSynced,
			&i.SkillCount,
			&i.Status,
			&i.ErrorMsg,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkillSourceStatus = `-- name: UpdateSkillSourceStatus :exec
UPDATE skill_sources
SET status = ?, error_msg = ?, skill_count = ?, last_synced = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSkillSourceStatusParams struct {
	Status     string         `json:"status"`
	ErrorMsg   sql.NullString `json:"error_msg"`
	SkillCount int64          `json:"skill_count"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateSkillSourceStatus(ctx context.Context, arg UpdateSkillSourceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSkillSourceStatus,
		arg.Status,
		arg.ErrorMsg,
		arg.SkillCount,
		arg.ID,
	)
	return err
}
