// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addAgentSkill = `-- name: AddAgentSkill :exec
INSERT INTO agent_skills (agent_id, skill_id, position, config_json)
VALUES (?, ?, ?, ?)
ON CONFLICT(agent_id, skill_id) DO UPDATE SET position = excluded.position, config_json = excluded.config_json
`

type AddAgentSkillParams struct {
	AgentID    string         `json:"agent_id"`
	SkillID    string         `json:"skill_id"`
	Position   int64          `json:"position"`
	ConfigJson sql.NullString `json:"config_json"`
}

func (q *Queries) AddAgentSkill(ctx context.Context, arg AddAgentSkillParams) error {
	_, err := q.db.ExecContext(ctx, addAgentSkill,
		arg.AgentID,
		arg.SkillID,
		arg.Position,
		arg.ConfigJson,
	)
	return err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (id, user_id, name, description, tier, version, skill_md, tags, source_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, source_id, name, description, tier, version, skill_md, tags, source_url, enabled, requires_env, created_at, updated_at
`

type CreateSkillParams struct {
	ID          string         `json:"id"`
	UserID      sql.NullString `json:"user_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Tier        string         `json:"tier"`
	Version     string         `json:"version"`
	SkillMd     string         `json:"skill_md"`
	Tags        string         `json:"tags"`
	SourceUrl   sql.NullString `json:"source_url"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, createSkill,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Tier,
		arg.Version,
		arg.SkillMd,
		arg.Tags,
		arg.SourceUrl,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Name,
		&i.Description,
		&i.Tier,
		&i.Version,
		&i.SkillMd,
		&i.Tags,
		&i.SourceUrl,
		&i.Enabled,
		&i.RequiresEnv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = ?
`

func (q *Queries) DeleteSkill(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSkill, id)
	return err
}

const deleteSkillsBySource = `-- name: DeleteSkillsBySource :exec
DELETE FROM skills WHERE source_id = ? AND id NOT IN (SELECT skill_id FROM agent_skills)
`

func (q *Queries) DeleteSkillsBySource(ctx context.Context, sourceID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteSkillsBySource, sourceID)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, user_id, source_id, name, description, tier, version, skill_md, tags, source_url, enabled, requires_env, created_at, updated_at FROM skills WHERE id = ?
`

func (q *Queries) GetSkill(ctx context.Context, id string) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkill, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceID,
		&i.Name,
		&i.Description,
		&i.Tier,
		&i.Version,
		&i.SkillMd,
		&i.Tags,
		&i.SourceUrl,
		&i.Enabled,
		&i.RequiresEnv,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentSkills = `-- name: ListAgentSkills :many
SELECT s.id, s.user_id, s.source_id, s.name, s.description, s.tier, s.version, s.skill_md, s.tags, s.source_url, s.enabled, s.requires_env, s.created_at, s.updated_at, ags.position, ags.config_json
FROM skills s
JOIN agent_skills ags ON ags.skill_id = s.id
WHERE ags.agent_id = ?
ORDER BY ags.position
`

type ListAgentSkillsRow struct {
	ID          string         `json:"id"`
	UserID      sql.NullString `json:"user_id"`
	SourceID    sql.NullString `json:"source_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Tier        string         `json:"tier"`
	Version     string         `json:"version"`
	SkillMd     string         `json:"skill_md"`
	Tags        string         `json:"tags"`
	SourceUrl   sql.NullString `json:"source_url"`
	Enabled     bool           `json:"enabled"`
	RequiresEnv string         `json:"requires_env"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Position    int64          `json:"position"`
	ConfigJson  sql.NullString `json:"config_json"`
}

func (q *Queries) ListAgentSkills(ctx context.Context, agentID string) ([]ListAgentSkillsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAgentSkills, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentSkillsRow{}
	for rows.Next() {
		var i ListAgentSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Name,
			&i.Description,
			&i.Tier,
			&i.Version,
			&i.SkillMd,
			&i.Tags,
			&i.SourceUrl,
			&i.Enabled,
			&i.RequiresEnv,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
			&i.ConfigJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT id, user_id, source_id, name, description, tier, version, skill_md, tags, source_url, enabled, requires_env, created_at, updated_at FROM skills WHERE enabled = true ORDER BY name
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Name,
			&i.Description,
			&i.Tier,
			&i.Version,
			&i.SkillMd,
			&i.Tags,
			&i.SourceUrl,
			&i.Enabled,
			&i.RequiresEnv,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByTier = `-- name: ListSkillsByTier :many
SELECT id, user_id, source_id, name, description, tier, version, skill_md, tags, source_url, enabled, requires_env, created_at, updated_at FROM skills WHERE tier = ? AND enabled = true ORDER BY name
`

func (q *Queries) ListSkillsByTier(ctx context.Context, tier string) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkillsByTier, tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Name,
			&i.Description,
			&i.Tier,
			&i.Version,
			&i.SkillMd,
			&i.Tags,
			&i.SourceUrl,
			&i.Enabled,
			&i.RequiresEnv,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByUser = `-- name: ListSkillsByUser :many
SELECT id, user_id, source_id, name, description, tier, version, skill_md, tags, source_url, enabled, requires_env, created_at, updated_at FROM skills WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListSkillsByUser(ctx context.Context, userID sql.NullString) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkillsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceID,
			&i.Name,
			&i.Description,
			&i.Tier,
			&i.Version,
			&i.SkillMd,
			&i.Tags,
			&i.SourceUrl,
			&i.Enabled,
			&i.RequiresEnv,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAgentSkill = `-- name: RemoveAgentSkill :exec
DELETE FROM agent_skills WHERE agent_id = ? AND skill_id = ?
`

type RemoveAgentSkillParams struct {
	AgentID string `json:"agent_id"`
	SkillID string `json:"skill_id"`
}

func (q *Queries) RemoveAgentSkill(ctx context.Context, arg RemoveAgentSkillParams) error {
	_, err := q.db.ExecContext(ctx, removeAgentSkill, arg.AgentID, arg.SkillID)
	return err
}

const updateSkill = `-- name: UpdateSkill :exec
UPDATE skills
SET name = ?, description = ?, skill_md = ?, tags = ?, enabled = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSkillParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	SkillMd     string `json:"skill_md"`
	Tags        string `json:"tags"`
	Enabled     bool   `json:"enabled"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) error {
	_, err := q.db.ExecContext(ctx, updateSkill,
		arg.Name,
		arg.Description,
		arg.SkillMd,
		arg.Tags,
		arg.Enabled,
		arg.ID,
	)
	return err
}

const upsertRegistrySkill = `-- name: UpsertRegistrySkill :exec
INSERT INTO skills (id, user_id, source_id, name, description, tier, version, skill_md, tags, source_url, requires_env, enabled)
VALUES (?, NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, true)
ON CONFLICT(id) DO UPDATE SET
  source_id = excluded.source_id,
  description = excluded.description,
  tier = excluded.tier,
  version = excluded.version,
  skill_md = excluded.skill_md,
  tags = excluded.tags,
  source_url = excluded.source_url,
  requires_env = excluded.requires_env,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertRegistrySkillParams struct {
	ID          string         `json:"id"`
	SourceID    sql.NullString `json:"source_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Tier        string         `json:"tier"`
	Version     string         `json:"version"`
	SkillMd     string         `json:"skill_md"`
	Tags        string         `json:"tags"`
	SourceUrl   sql.NullString `json:"source_url"`
	RequiresEnv string         `json:"requires_env"`
}

func (q *Queries) UpsertRegistrySkill(ctx context.Context, arg UpsertRegistrySkillParams) error {
	_, err := q.db.ExecContext(ctx, upsertRegistrySkill,
		arg.ID,
		arg.SourceID,
		arg.Name,
		arg.Description,
		arg.Tier,
		arg.Version,
		arg.SkillMd,
		arg.Tags,
		arg.SourceUrl,
		arg.RequiresEnv,
	)
	return err
}
