// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countRunsByStatus = `-- name: CountRunsByStatus :many
SELECT status, COUNT(*) as count
FROM runs
WHERE agent_id IN (SELECT id FROM agents WHERE user_id = ?)
GROUP BY status
`

type CountRunsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountRunsByStatus(ctx context.Context, userID string) ([]CountRunsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countRunsByStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRunsByStatusRow{}
	for rows.Next() {
		var i CountRunsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentRuns = `-- name: RecentRuns :many
SELECT r.id, r.agent_id, r.mission, r.model_provider, r.model_name, r.status, r.output_text, r.error_message, r.total_turns, r.input_tokens, r.output_tokens, r.cost_usd, r.duration_ms, r.created_at, r.started_at, r.completed_at, a.name as agent_name
FROM runs r
JOIN agents a ON a.id = r.agent_id
WHERE a.user_id = ?
ORDER BY r.created_at DESC
LIMIT ?
`

type RecentRunsParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

type RecentRunsRow struct {
	ID            string          `json:"id"`
	AgentID       string          `json:"agent_id"`
	Mission       string          `json:"mission"`
	ModelProvider string          `json:"model_provider"`
	ModelName     string          `json:"model_name"`
	Status        string          `json:"status"`
	OutputText    sql.NullString  `json:"output_text"`
	ErrorMessage  sql.NullString  `json:"error_message"`
	TotalTurns    sql.NullInt64   `json:"total_turns"`
	InputTokens   sql.NullInt64   `json:"input_tokens"`
	OutputTokens  sql.NullInt64   `json:"output_tokens"`
	CostUsd       sql.NullFloat64 `json:"cost_usd"`
	DurationMs    sql.NullInt64   `json:"duration_ms"`
	CreatedAt     time.Time       `json:"created_at"`
	StartedAt     sql.NullTime    `json:"started_at"`
	CompletedAt   sql.NullTime    `json:"completed_at"`
	AgentName     string          `json:"agent_name"`
}

func (q *Queries) RecentRuns(ctx context.Context, arg RecentRunsParams) ([]RecentRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, recentRuns, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentRunsRow{}
	for rows.Next() {
		var i RecentRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Mission,
			&i.ModelProvider,
			&i.ModelName,
			&i.Status,
			&i.OutputText,
			&i.ErrorMessage,
			&i.TotalTurns,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.DurationMs,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.AgentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
