// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id, role) VALUES (?, ?, ?)
`

type AddTeamMemberParams struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const countChildRuns = `-- name: CountChildRuns :one
SELECT COUNT(*) FROM runs WHERE parent_run_id = ?
`

func (q *Queries) CountChildRuns(ctx context.Context, parentRunID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildRuns, parentRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO team_invitations (id, team_id, email, role, invited_by, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, team_id, email, role, invited_by, status, expires_at, created_at
`

type CreateInvitationParams struct {
	ID        string    `json:"id"`
	TeamID    string    `json:"team_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	InvitedBy string    `json:"invited_by"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (TeamInvitation, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.ID,
		arg.TeamID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i TeamInvitation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, name, slug, owner_id)
VALUES (?, ?, ?, ?)
RETURNING id, name, slug, owner_id, created_at, updated_at
`

type CreateTeamParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Slug    string `json:"slug"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.OwnerID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = ?
`

func (q *Queries) DeleteTeam(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTeam, id)
	return err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, team_id, email, role, invited_by, status, expires_at, created_at FROM team_invitations WHERE id = ?
`

func (q *Queries) GetInvitation(ctx context.Context, id string) (TeamInvitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitation, id)
	var i TeamInvitation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, slug, owner_id, created_at, updated_at FROM teams WHERE id = ?
`

func (q *Queries) GetTeam(ctx context.Context, id string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, name, slug, owner_id, created_at, updated_at FROM teams WHERE slug = ?
`

func (q *Queries) GetTeamBySlug(ctx context.Context, slug string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamBySlug, slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT team_id, user_id, role, joined_at FROM team_members WHERE team_id = ? AND user_id = ?
`

type GetTeamMemberParams struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listChildRuns = `-- name: ListChildRuns :many
SELECT id, agent_id, team_id, parent_run_id, depth, mission, model_provider, model_name, status, output_text, error_message, total_turns, input_tokens, output_tokens, cost_usd, duration_ms, created_at, started_at, completed_at FROM runs WHERE parent_run_id = ? ORDER BY created_at
`

func (q *Queries) ListChildRuns(ctx context.Context, parentRunID sql.NullString) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listChildRuns, parentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TeamID,
			&i.ParentRunID,
			&i.Depth,
			&i.Mission,
			&i.ModelProvider,
			&i.ModelName,
			&i.Status,
			&i.OutputText,
			&i.ErrorMessage,
			&i.TotalTurns,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.DurationMs,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT id, team_id, email, role, invited_by, status, expires_at, created_at FROM team_invitations WHERE team_id = ? AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitations(ctx context.Context, teamID string) ([]TeamInvitation, error) {
	rows, err := q.db.QueryContext(ctx, listPendingInvitations, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamInvitation{}
	for rows.Next() {
		var i TeamInvitation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.team_id, tm.user_id, tm.role, tm.joined_at, u.email, u.name as user_name, u.avatar_url
FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = ?
ORDER BY tm.joined_at
`

type ListTeamMembersRow struct {
	TeamID    string         `json:"team_id"`
	UserID    string         `json:"user_id"`
	Role      string         `json:"role"`
	JoinedAt  time.Time      `json:"joined_at"`
	Email     string         `json:"email"`
	UserName  string         `json:"user_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID string) ([]ListTeamMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.UserName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT t.id, t.name, t.slug, t.owner_id, t.created_at, t.updated_at FROM teams t
JOIN team_members tm ON tm.team_id = t.id
WHERE tm.user_id = ?
ORDER BY t.name
`

func (q *Queries) ListUserTeams(ctx context.Context, userID string) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = ? AND user_id = ?
`

type RemoveTeamMemberParams struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :exec
UPDATE team_invitations SET status = ? WHERE id = ?
`

type UpdateInvitationStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInvitationStatus, arg.Status, arg.ID)
	return err
}

const updateTeam = `-- name: UpdateTeam :exec
UPDATE teams SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateTeamParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) error {
	_, err := q.db.ExecContext(ctx, updateTeam, arg.Name, arg.ID)
	return err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :exec
UPDATE team_members SET role = ? WHERE team_id = ? AND user_id = ?
`

type UpdateTeamMemberRoleParams struct {
	Role   string `json:"role"`
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateTeamMemberRole, arg.Role, arg.TeamID, arg.UserID)
	return err
}
