// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createStepRun = `-- name: CreateStepRun :one
INSERT INTO workflow_step_runs (id, workflow_run_id, step_id, status)
VALUES (?, ?, ?, 'pending')
RETURNING id, workflow_run_id, step_id, run_id, status, started_at, completed_at
`

type CreateStepRunParams struct {
	ID            string `json:"id"`
	WorkflowRunID string `json:"workflow_run_id"`
	StepID        string `json:"step_id"`
}

func (q *Queries) CreateStepRun(ctx context.Context, arg CreateStepRunParams) (WorkflowStepRun, error) {
	row := q.db.QueryRowContext(ctx, createStepRun, arg.ID, arg.WorkflowRunID, arg.StepID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepID,
		&i.RunID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (id, user_id, team_id, name, description)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, team_id, name, description, enabled, created_at, updated_at
`

type CreateWorkflowParams struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	TeamID      sql.NullString `json:"team_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, createWorkflow,
		arg.ID,
		arg.UserID,
		arg.TeamID,
		arg.Name,
		arg.Description,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (id, workflow_id, user_id, status, input_text)
VALUES (?, ?, ?, 'pending', ?)
RETURNING id, workflow_id, user_id, status, input_text, output_text, error_message, created_at, started_at, completed_at
`

type CreateWorkflowRunParams struct {
	ID         string `json:"id"`
	WorkflowID string `json:"workflow_id"`
	UserID     string `json:"user_id"`
	InputText  string `json:"input_text"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowRun,
		arg.ID,
		arg.WorkflowID,
		arg.UserID,
		arg.InputText,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.UserID,
		&i.Status,
		&i.InputText,
		&i.OutputText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createWorkflowStep = `-- name: CreateWorkflowStep :one
INSERT INTO workflow_steps (id, workflow_id, agent_id, name, position, mission_template, depends_on)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, workflow_id, agent_id, name, position, mission_template, depends_on, created_at
`

type CreateWorkflowStepParams struct {
	ID              string `json:"id"`
	WorkflowID      string `json:"workflow_id"`
	AgentID         string `json:"agent_id"`
	Name            string `json:"name"`
	Position        int64  `json:"position"`
	MissionTemplate string `json:"mission_template"`
	DependsOn       string `json:"depends_on"`
}

func (q *Queries) CreateWorkflowStep(ctx context.Context, arg CreateWorkflowStepParams) (WorkflowStep, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowStep,
		arg.ID,
		arg.WorkflowID,
		arg.AgentID,
		arg.Name,
		arg.Position,
		arg.MissionTemplate,
		arg.DependsOn,
	)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Name,
		&i.Position,
		&i.MissionTemplate,
		&i.DependsOn,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows WHERE id = ? AND user_id = ?
`

type DeleteWorkflowParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflow, arg.ID, arg.UserID)
	return err
}

const deleteWorkflowStep = `-- name: DeleteWorkflowStep :exec
DELETE FROM workflow_steps WHERE id = ?
`

func (q *Queries) DeleteWorkflowStep(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowStep, id)
	return err
}

const deleteWorkflowSteps = `-- name: DeleteWorkflowSteps :exec
DELETE FROM workflow_steps WHERE workflow_id = ?
`

func (q *Queries) DeleteWorkflowSteps(ctx context.Context, workflowID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflowSteps, workflowID)
	return err
}

const getStepRunByStepID = `-- name: GetStepRunByStepID :one
SELECT id, workflow_run_id, step_id, run_id, status, started_at, completed_at FROM workflow_step_runs
WHERE workflow_run_id = ? AND step_id = ?
`

type GetStepRunByStepIDParams struct {
	WorkflowRunID string `json:"workflow_run_id"`
	StepID        string `json:"step_id"`
}

func (q *Queries) GetStepRunByStepID(ctx context.Context, arg GetStepRunByStepIDParams) (WorkflowStepRun, error) {
	row := q.db.QueryRowContext(ctx, getStepRunByStepID, arg.WorkflowRunID, arg.StepID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepID,
		&i.RunID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, user_id, team_id, name, description, enabled, created_at, updated_at FROM workflows WHERE id = ?
`

func (q *Queries) GetWorkflow(ctx context.Context, id string) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, workflow_id, user_id, status, input_text, output_text, error_message, created_at, started_at, completed_at FROM workflow_runs WHERE id = ?
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id string) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.UserID,
		&i.Status,
		&i.InputText,
		&i.OutputText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWorkflowStep = `-- name: GetWorkflowStep :one
SELECT id, workflow_id, agent_id, name, position, mission_template, depends_on, created_at FROM workflow_steps WHERE id = ?
`

func (q *Queries) GetWorkflowStep(ctx context.Context, id string) (WorkflowStep, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowStep, id)
	var i WorkflowStep
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Name,
		&i.Position,
		&i.MissionTemplate,
		&i.DependsOn,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingStepRuns = `-- name: ListPendingStepRuns :many
SELECT sr.id, sr.workflow_run_id, sr.step_id, sr.run_id, sr.status, sr.started_at, sr.completed_at, ws.name as step_name, ws.agent_id, ws.mission_template, ws.depends_on
FROM workflow_step_runs sr
JOIN workflow_steps ws ON sr.step_id = ws.id
WHERE sr.workflow_run_id = ? AND sr.status = 'pending'
ORDER BY ws.position
`

type ListPendingStepRunsRow struct {
	ID              string         `json:"id"`
	WorkflowRunID   string         `json:"workflow_run_id"`
	StepID          string         `json:"step_id"`
	RunID           sql.NullString `json:"run_id"`
	Status          string         `json:"status"`
	StartedAt       sql.NullTime   `json:"started_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	StepName        string         `json:"step_name"`
	AgentID         string         `json:"agent_id"`
	MissionTemplate string         `json:"mission_template"`
	DependsOn       string         `json:"depends_on"`
}

func (q *Queries) ListPendingStepRuns(ctx context.Context, workflowRunID string) ([]ListPendingStepRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingStepRuns, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingStepRunsRow{}
	for rows.Next() {
		var i ListPendingStepRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.StepID,
			&i.RunID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.StepName,
			&i.AgentID,
			&i.MissionTemplate,
			&i.DependsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepRuns = `-- name: ListStepRuns :many
SELECT sr.id, sr.workflow_run_id, sr.step_id, sr.run_id, sr.status, sr.started_at, sr.completed_at, ws.name as step_name, ws.agent_id, ws.depends_on
FROM workflow_step_runs sr
JOIN workflow_steps ws ON sr.step_id = ws.id
WHERE sr.workflow_run_id = ?
ORDER BY ws.position
`

type ListStepRunsRow struct {
	ID            string         `json:"id"`
	WorkflowRunID string         `json:"workflow_run_id"`
	StepID        string         `json:"step_id"`
	RunID         sql.NullString `json:"run_id"`
	Status        string         `json:"status"`
	StartedAt     sql.NullTime   `json:"started_at"`
	CompletedAt   sql.NullTime   `json:"completed_at"`
	StepName      string         `json:"step_name"`
	AgentID       string         `json:"agent_id"`
	DependsOn     string         `json:"depends_on"`
}

func (q *Queries) ListStepRuns(ctx context.Context, workflowRunID string) ([]ListStepRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStepRuns, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepRunsRow{}
	for rows.Next() {
		var i ListStepRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.StepID,
			&i.RunID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.StepName,
			&i.AgentID,
			&i.DependsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT id, workflow_id, user_id, status, input_text, output_text, error_message, created_at, started_at, completed_at FROM workflow_runs WHERE workflow_id = ?
ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListWorkflowRunsParams struct {
	WorkflowID string `json:"workflow_id"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) ListWorkflowRuns(ctx context.Context, arg ListWorkflowRunsParams) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowRuns, arg.WorkflowID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowRun{}
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.UserID,
			&i.Status,
			&i.InputText,
			&i.OutputText,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowSteps = `-- name: ListWorkflowSteps :many
SELECT ws.id, ws.workflow_id, ws.agent_id, ws.name, ws.position, ws.mission_template, ws.depends_on, ws.created_at, a.name as agent_name FROM workflow_steps ws
JOIN agents a ON ws.agent_id = a.id
WHERE ws.workflow_id = ?
ORDER BY ws.position
`

type ListWorkflowStepsRow struct {
	ID              string    `json:"id"`
	WorkflowID      string    `json:"workflow_id"`
	AgentID         string    `json:"agent_id"`
	Name            string    `json:"name"`
	Position        int64     `json:"position"`
	MissionTemplate string    `json:"mission_template"`
	DependsOn       string    `json:"depends_on"`
	CreatedAt       time.Time `json:"created_at"`
	AgentName       string    `json:"agent_name"`
}

func (q *Queries) ListWorkflowSteps(ctx context.Context, workflowID string) ([]ListWorkflowStepsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowSteps, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowStepsRow{}
	for rows.Next() {
		var i ListWorkflowStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.AgentID,
			&i.Name,
			&i.Position,
			&i.MissionTemplate,
			&i.DependsOn,
			&i.CreatedAt,
			&i.AgentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowsByUser = `-- name: ListWorkflowsByUser :many
SELECT id, user_id, team_id, name, description, enabled, created_at, updated_at FROM workflows WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflowsByUser(ctx context.Context, userID string) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStepRun = `-- name: UpdateStepRun :exec
UPDATE workflow_step_runs SET run_id = ?, status = ?, started_at = ?, completed_at = ?
WHERE id = ?
`

type UpdateStepRunParams struct {
	RunID       sql.NullString `json:"run_id"`
	Status      string         `json:"status"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateStepRun(ctx context.Context, arg UpdateStepRunParams) error {
	_, err := q.db.ExecContext(ctx, updateStepRun,
		arg.RunID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}

const updateWorkflow = `-- name: UpdateWorkflow :exec
UPDATE workflows SET name = ?, description = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateWorkflowParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Enabled     bool   `json:"enabled"`
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflow,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateWorkflowRunStatus = `-- name: UpdateWorkflowRunStatus :exec
UPDATE workflow_runs SET status = ?, started_at = ?, completed_at = ?, output_text = ?, error_message = ?
WHERE id = ?
`

type UpdateWorkflowRunStatusParams struct {
	Status       string         `json:"status"`
	StartedAt    sql.NullTime   `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
	OutputText   sql.NullString `json:"output_text"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateWorkflowRunStatus(ctx context.Context, arg UpdateWorkflowRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowRunStatus,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.OutputText,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const updateWorkflowStep = `-- name: UpdateWorkflowStep :exec
UPDATE workflow_steps SET agent_id = ?, name = ?, position = ?, mission_template = ?, depends_on = ?
WHERE id = ?
`

type UpdateWorkflowStepParams struct {
	AgentID         string `json:"agent_id"`
	Name            string `json:"name"`
	Position        int64  `json:"position"`
	MissionTemplate string `json:"mission_template"`
	DependsOn       string `json:"depends_on"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateWorkflowStep(ctx context.Context, arg UpdateWorkflowStepParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowStep,
		arg.AgentID,
		arg.Name,
		arg.Position,
		arg.MissionTemplate,
		arg.DependsOn,
		arg.ID,
	)
	return err
}
